/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liu_opencvdemo_utils_NativeUtils */

#ifndef _Included_com_liu_opencvdemo_utils_NativeUtils
#define _Included_com_liu_opencvdemo_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liu_opencvdemo_utils_NativeUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liu_opencvdemo_utils_NativeUtils_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_liu_opencvdemo_utils_NativeUtils
 * Method:    testPio
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_liu_opencvdemo_utils_NativeUtils_testPio
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
